### ISSUE TITLE
Beautify the UI

### ISSUE THREAD

**Issue by seanfirefox** [seanfirefox/TheGrumpyNUSFreshman#4]
The default manifest header and default buttons should be customised as they are affecting the overall aesthetics of the app.

**Comment by russelltankaimin** [comment]
Let's leave this to Milestone 3.
Funny enough : Some group said our UI is very neat and makes it very easy to use. However, another team said it could be neater. But since it's Orbital, we could explore Materials UI that Boon recommended

**Comment by russelltankaimin** [comment]
Planning to experiment Material Design on Login Page first. Doing it on new Branch Material UI

**Comment by russelltankaimin** [comment]
Login Page done

**Comment by russelltankaimin** [comment]
Register Page Done

**Comment by seanfirefox** [comment]
Landing Page Done

**Comment by seanfirefox** [comment]
To Do List Main Page Done

**Comment by russelltankaimin** [comment]
Milestone Page Done

**Comment by russelltankaimin** [comment]
Add Task / Edit Task Activity Page done

**Comment by russelltankaimin** [comment]
Settings Activity done

**Comment by seanfirefox** [comment]
Calendar Activity done

**Comment by seanfirefox** [comment]
Generate Timetable Activity done

**Comment by russelltankaimin** [comment]
Generally done, may include more items in the future if there is time.
