### ISSUE TITLE
[ContentMainActivity] Announcements should have displayed expired task too

### ISSUE THREAD

**Issue by russelltankaimin** [seanfirefox/TheGrumpyNUSFreshman#45]
A note from my brother after a bit of user testing : 
Since you guys are using icons to your advantage, might as well display expired tasks? Then the colour of the ICONs for the card to be as such 

- Still got time - GREEN
- GOING TO DUE in < 1 day - ORANGE
- EXPIRED - RED

For your consideration

**Comment by seanfirefox** [comment]
Added functionality.
